# Generated by Django 2.2.1 on 2019-05-14 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', help_text="User's village name", max_length=50)),
                ('village', models.CharField(default='', help_text="User's city name", max_length=50)),
                ('district', models.CharField(help_text="User's district name", max_length=50, null=True)),
                ('state', models.CharField(blank=True, help_text="User's state name", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="User's fisrt name", max_length=50)),
                ('last_name', models.CharField(help_text="User's last name", max_length=50)),
                ('date_of_birth', models.DateField(help_text="User's date of birth")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='User created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='User details last updated at')),
                ('active', models.BooleanField(default=True, help_text='Active status')),
                ('address', models.ForeignKey(help_text="User's address", on_delete=django.db.models.deletion.CASCADE, to='users.Address')),
            ],
        ),
    ]
