# Generated by Django 2.2.1 on 2019-05-14 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of category', max_length=50)),
                ('description', models.TextField(default='', help_text='Description of category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text="Post's title", max_length=50)),
                ('description', models.TextField(help_text="Post's description")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Post created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Post last updated at')),
                ('active', models.BooleanField(default=True, help_text='Active status')),
                ('category', models.ForeignKey(help_text='Post belongs to', on_delete=django.db.models.deletion.CASCADE, to='posts.Category')),
                ('posted_by', models.ForeignKey(help_text='Posted by (Who posted this post)', on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
